#!/usr/bin/env python3
"""
Build an ATT&CK Navigator layer from the framework's technique references.

Scans every file under red-team/ for MITRE ATT&CK technique IDs, tallies how
many times (and where) each is referenced, and emits a Navigator layer JSON.

Import the output at the official Navigator to see coverage as a heatmap:
    https://mitre-attack.github.io/attack-navigator/
    → Open Existing Layer → Upload from local → navigator-layer.json

The reference for all technique IDs is https://attack.mitre.org/ (Enterprise).
"""

import json
import re
from pathlib import Path
from collections import defaultdict

RED_TEAM_DIR = Path(__file__).parent.parent
OUT_FILE = Path(__file__).parent / "navigator-layer.json"

# Valid Enterprise technique / sub-technique IDs: TNNNN or TNNNN.NNN
TECHNIQUE_RE = re.compile(r"\bT\d{4}(?:\.\d{3})?\b")

# Tag each reference by the part of the framework it comes from, so the
# Navigator tooltip shows *why* a technique is in scope.
SOURCE_TAGS = [
    ("scenarios/", "scenario"),
    ("threat-actors.json", "actor-TTP"),
    ("mitre-attack/framework.json", "coverage-map"),
    ("detection-mapping/", "detection"),
    ("reconnaissance/", "recon"),
]

# Don't scan the generator's own output or this script.
SKIP_NAMES = {OUT_FILE.name, Path(__file__).name}


def classify(path_str):
    for needle, tag in SOURCE_TAGS:
        if needle in path_str:
            return tag
    return "other"


def scan():
    counts = defaultdict(int)
    sources = defaultdict(set)

    for path in sorted(RED_TEAM_DIR.rglob("*")):
        if not path.is_file() or path.name in SKIP_NAMES:
            continue
        if path.suffix not in {".json", ".md", ".py"}:
            continue
        rel = str(path.relative_to(RED_TEAM_DIR))
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        tag = classify(rel)
        for tid in TECHNIQUE_RE.findall(text):
            counts[tid] += 1
            sources[tid].add(tag)

    return counts, sources


def build_layer(counts, sources):
    max_score = max(counts.values()) if counts else 1

    techniques = []
    for tid in sorted(counts):
        tags = ", ".join(sorted(sources[tid]))
        techniques.append({
            "techniqueID": tid,
            "score": counts[tid],
            "comment": f"Referenced in: {tags} ({counts[tid]} mention(s))",
            "enabled": True,
            "metadata": [{"name": "framework-source", "value": tags}],
        })

    return {
        "name": "Random-Stuff Red-Team Coverage",
        "versions": {"attack": "14", "navigator": "4.9.1", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": (
            "Techniques referenced across the intelligence-led red-team "
            "framework (scenarios, threat-actor TTPs, coverage map, detection "
            "hunts, reconnaissance). Score = number of references. Generated by "
            "build-navigator-layer.py. Reference: https://attack.mitre.org/"
        ),
        "techniques": techniques,
        "gradient": {
            "colors": ["#ffe0e0", "#ff6666", "#b30000"],
            "minValue": 0,
            "maxValue": max_score,
        },
        "legendItems": [
            {"label": "1-2 refs (single use)", "color": "#ffe0e0"},
            {"label": "mid coverage", "color": "#ff6666"},
            {"label": f"{max_score} refs (most reinforced)", "color": "#b30000"},
        ],
        "sorting": 3,
        "hideDisabled": False,
        "showTacticRowBackground": True,
        "tacticRowBackground": "#205b8f",
    }


def main():
    counts, sources = scan()
    layer = build_layer(counts, sources)

    with open(OUT_FILE, "w") as f:
        json.dump(layer, f, indent=2)
        f.write("\n")

    uniq = len(counts)
    subs = sum(1 for t in counts if "." in t)
    print(f"✅ Wrote {OUT_FILE.name}")
    print(f"   {uniq} unique techniques ({subs} sub-techniques), "
          f"{sum(counts.values())} total references")
    print(f"   Most-referenced: "
          + ", ".join(f"{t}×{c}" for t, c in
                      sorted(counts.items(), key=lambda kv: -kv[1])[:5]))
    print(f"\n   Import at https://mitre-attack.github.io/attack-navigator/")
    print(f"   → Open Existing Layer → Upload from local → {OUT_FILE.name}")


if __name__ == "__main__":
    main()
