"""
`rt navigator` — build an ATT&CK Navigator layer from the framework's technique
references. Import the output at https://mitre-attack.github.io/attack-navigator/
"""

import argparse
from collections import defaultdict

import attack

# Tag each reference by the part of the framework it comes from.
SOURCE_TAGS = [
    ("scenarios/", "scenario"),
    ("threat-actors.json", "actor-TTP"),
    ("campaigns/", "campaign"),
    ("mitre-attack/framework.json", "coverage-map"),
    ("detection-mapping/", "detection"),
    ("reconnaissance/", "recon"),
]


def _classify(rel):
    for needle, tag in SOURCE_TAGS:
        if needle in rel:
            return tag
    return "other"


def scan():
    counts = defaultdict(int)
    sources = defaultdict(set)
    for path in sorted(attack.RED_TEAM_DIR.rglob("*")):
        # Data + docs only; skip the tools/ code and the generated layer.
        if not path.is_file() or path.suffix not in {".json", ".md"}:
            continue
        if path == attack.NAVIGATOR_LAYER_FILE:
            continue
        rel = str(path.relative_to(attack.RED_TEAM_DIR))
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        tag = _classify(rel)
        for tid in attack.extract_techniques(text):
            counts[tid] += 1
            sources[tid].add(tag)
    return counts, sources


def build_layer(counts, sources):
    max_score = max(counts.values()) if counts else 1
    techniques = []
    for tid in sorted(counts):
        tags = ", ".join(sorted(sources[tid]))
        techniques.append({
            "techniqueID": tid,
            "score": counts[tid],
            "comment": f"Referenced in: {tags} ({counts[tid]} mention(s))",
            "enabled": True,
            "metadata": [{"name": "framework-source", "value": tags}],
        })
    return {
        "name": "Random-Stuff Red-Team Coverage",
        "versions": {"attack": "14", "navigator": "4.9.1", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": (
            "Techniques referenced across the intelligence-led red-team "
            "framework (scenarios, threat-actor TTPs, campaigns, coverage map, "
            "detection hunts, reconnaissance). Score = number of references. "
            "Generated by tools/navigator.py. Reference: https://attack.mitre.org/"
        ),
        "techniques": techniques,
        "gradient": {"colors": ["#ffe0e0", "#ff6666", "#b30000"],
                     "minValue": 0, "maxValue": max_score},
        "legendItems": [
            {"label": "1-2 refs (single use)", "color": "#ffe0e0"},
            {"label": "mid coverage", "color": "#ff6666"},
            {"label": f"{max_score} refs (most reinforced)", "color": "#b30000"},
        ],
        "sorting": 3,
        "hideDisabled": False,
        "showTacticRowBackground": True,
        "tacticRowBackground": "#205b8f",
    }


def build():
    counts, sources = scan()
    attack.dump_json(build_layer(counts, sources), attack.NAVIGATOR_LAYER_FILE)
    uniq = len(counts)
    subs = sum(1 for t in counts if "." in t)
    top = ", ".join(f"{t}×{c}" for t, c in sorted(counts.items(), key=lambda kv: -kv[1])[:5])
    print(f"✅ Wrote {attack.NAVIGATOR_LAYER_FILE.name}")
    print(f"   {uniq} unique techniques ({subs} sub-techniques), "
          f"{sum(counts.values())} total references")
    print(f"   Most-referenced: {top}")
    print("\n   Import at https://mitre-attack.github.io/attack-navigator/")
    print(f"   → Open Existing Layer → Upload from local → {attack.NAVIGATOR_LAYER_FILE.name}")


# --- CLI wiring -------------------------------------------------------------
def add_arguments(p):
    pass  # no options; building the layer is the only action


def handle(args):
    build()


def register(subparsers):
    p = subparsers.add_parser("navigator", help="Build the ATT&CK Navigator coverage layer")
    add_arguments(p)
    p.set_defaults(func=handle)


def main():
    argparse.ArgumentParser(description="Build ATT&CK Navigator layer").parse_args()
    build()


if __name__ == "__main__":
    main()
