pub mod models;
pub mod sources;
pub mod aggregator;
pub mod cache;
pub mod threat_feeds;
pub mod multi_source;
pub mod config;
pub mod correlation;
pub mod geolocation;
pub mod attribution;
pub mod detection_rules;
pub mod timeline;
pub mod threat_emulation;
pub mod incident_mapping;
pub mod campaign_planner;
pub mod supply_chain;

pub use models::{OsintEntity, EntityType, OsintResult, BreachData, ThreatIndicator};
pub use sources::{DataSource, DataSourceType, MockDataSource, HaveIBeenPwnedSource, VirusTotalSource, IPReputationSource};
pub use aggregator::OsintAggregator;
pub use cache::OsintCache;
pub use threat_feeds::{ThreatIntelligenceFeed, ThreatActor};
pub use multi_source::{MultiSourceAggregator, EntityEnrichment};
pub use config::OsintApiConfig;
pub use correlation::{CorrelationEngine, CorrelationLink, TTPPattern, ActorNetwork};
pub use geolocation::{GeolocationEngine, GeoLocation, BreachVictimData, GeolocationEnrichment};
pub use attribution::{AttributionEngine, CampaignAttribution, IncidentProfile};
pub use detection_rules::{DetectionRuleGenerator, DetectionRule, DetectionRuleset, RuleFormat, TuningGuidance};
pub use timeline::{TimelineAnalyzer, AttackTimeline, CampaignTimeline, TimelineEvent, AttackStage};
pub use threat_emulation::{ThreatEmulator, AttackScenario, ReconPlan, TargetProfile, DeliveryVector};
pub use incident_mapping::{IncidentMapper, ScenarioIncident, IncidentChain, ActorScenarioMapping};
pub use campaign_planner::{CampaignPlanner, CampaignStrategy, CampaignPhase, AnomalyWindow};
pub use supply_chain::{SupplyChainPlanner, VendorTarget, CompromiseStrategy, MalwareStaging};
